dev:
  database:
    name: tasklogs
    type: mysql
    host: localhost
    port: 3306
    username: tasklogs
    password: password
prod:
  heroku:
    key: 123
  database:
    name: tasklogs
    type: postgres
    host: tasklogs-database.amazonaws.com
    port: 5432
    username: tasklogs
    password: password